[package]
name = "managed-lhapdf"
version = "0.2.4"
authors = ["Christopher Schwan <handgranaten-herbert@posteo.de>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/cschwan/managed-lhapdf"
readme = "README.md"
keywords = ["high-energy-physics", "physics"]
categories = ["science"]
description = "(Unofficial) Rust bindings for the LHAPDF C++ library"
rust-version = "1.70.0"

[dependencies]
anyhow = "1.0.81"
cxx = "1.0.107"
dirs = "5.0.1"
serde = { features = ["derive"], version = "1.0.195" }
thiserror = "1.0"
toml = { features = ["display", "parse"], version = "0.8.12" }

[build-dependencies]
cxx-build = "1.0.107"
pkg-config = "0.3"

[features]
docs-only = []

[package.metadata.docs.rs]
features = [ "docs-only" ]
